1. Импортируйте Pandas в Jupyter Notebook.

In [1]:
%pip install pandas numpy

import numpy as np
import pandas as pd

Requirement already satisfied: pandas in d:\users\dmitriy\appdata\local\programs\python\python313\lib\site-packages (3.0.1)
Requirement already satisfied: numpy in d:\users\dmitriy\appdata\local\programs\python\python313\lib\site-packages (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dmitriy\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in d:\users\dmitriy\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\dmitriy\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

# 1. Основыные методы работы с dataframe.

2. Создайте DataFrame из словаря, где ключами будут названия столбцов, а значениями - списки значений этих столбцов.

In [2]:
data = {
    'Name': ['Alica', 'Boris', 'Slava', 'Dmitriy', 'Evgenia','Boris','Dmitriy'],
    'last_name':['Larin','Ivanov','Sidorov','Alekseev','Petrov', 'Lebedev', 'Aksenov'],
    'Age': [24, 27, 22, 32, 29, 44, 15],
    'City': ['Moscow', 'Moscow', 'Saint Peterburg', np.nan, 'Moscow', 'Saint Peterburg','Saint Peterburg'],
    'is_closed': [False, True, False, True, False,  True, False],
    'home_town':['Samara', 'Saratov', 'Saint Peterburg', np.nan, 'Moscow', 'Moscow','Kirov'],
    'in_group':[True, True, False, False, True, True, False],
    'male_dummy':[0, 1, 1, 1, 0, 1, 1],
    'likes_memes':[5, 8, 44, np.nan, 1, 12, 11]
}

In [3]:
df = pd.DataFrame(data)
df

,Name,last_name,Age,City,is_closed,home_town,in_group,male_dummy,likes_memes
0,Alica,Larin,24,Moscow,False,Samara,True,0,5.0
1,Boris,Ivanov,27,Moscow,True,Saratov,True,1,8.0
2,Slava,Sidorov,22,Saint Peterburg,False,Saint Peterburg,False,1,44.0
3,Dmitriy,Alekseev,32,NaN,True,NaN,False,1,NaN
4,Evgenia,Petrov,29,Moscow,False,Moscow,True,0,1.0
5,Boris,Lebedev,44,Saint Peterburg,True,Moscow,True,1,12.0
6,Dmitriy,Aksenov,15,Saint Peterburg,False,Kirov,False,1,11.0

3. Сохраните DataFrame в CSV-файл.

Сохраните созданный датафрейм в файл people.csv (.to_csv()).

In [4]:
df.to_csv("people.csv", index=False)

4. Загрузите данные из созданного CSV-файла people.csv в новый DataFrame с именем df и проверьте его содержимое с помощью командой pd.read_csv().

Аргументов у нее очень много, критически важные:

- filepath_or_buffer - текстовая строка с названием (адресом) файла
- sep - разделитель между данными
- header - номер строки, в которой в файле указаны названия столбцов, None, если нет
- names - список с названиями колонок
- index_col - или номер столбца, или список, или ничего - названия строк

In [5]:
df = pd.read_csv("people.csv", sep=",", header=0)
df

,Name,last_name,Age,City,is_closed,home_town,in_group,male_dummy,likes_memes
0,Alica,Larin,24,Moscow,False,Samara,True,0,5.0
1,Boris,Ivanov,27,Moscow,True,Saratov,True,1,8.0
2,Slava,Sidorov,22,Saint Peterburg,False,Saint Peterburg,False,1,44.0
3,Dmitriy,Alekseev,32,NaN,True,NaN,False,1,NaN
4,Evgenia,Petrov,29,Moscow,False,Moscow,True,0,1.0
5,Boris,Lebedev,44,Saint Peterburg,True,Moscow,True,1,12.0
6,Dmitriy,Aksenov,15,Saint Peterburg,False,Kirov,False,1,11.0

---

Есть несколько методов, которые мы используем сразу, как загрузили файл:
- [head()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.head.html): выводит первые 5 строк таблицы. Если задать в скобках число, то покажет ровно столько строк :)
- [info()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.info.html): показывает сводную информацию о таблице; сколько записей, сколько колонок, сколько непустых записей в таблице,
- [tail()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.tail.html): работает как head(), только наоборот, печатает с конца

На всякий случай, это **методы**. Их можно применять к датафрейму и столбцу, т.е. используем их так: <br>
**[Имя датафрейма].[Название метода с круглыми скобками]**
- df.head()
- df.tail()
- df.info()

----


На основную информацию по столбцам можно посмотреть с помощью метода `.info()`. Напротив каждого названия столбца можно увидеть, сколько в нём заполненных ячеек.

5. Выведите на экран первые и последние 3 строки DataFrame.

In [6]:
df.head(3)

,Name,last_name,Age,City,is_closed,home_town,in_group,male_dummy,likes_memes
0,Alica,Larin,24,Moscow,False,Samara,True,0,5.0
1,Boris,Ivanov,27,Moscow,True,Saratov,True,1,8.0
2,Slava,Sidorov,22,Saint Peterburg,False,Saint Peterburg,False,1,44.0

In [7]:
df.tail(3)

,Name,last_name,Age,City,is_closed,home_town,in_group,male_dummy,likes_memes
4,Evgenia,Petrov,29,Moscow,False,Moscow,True,0,1.0
5,Boris,Lebedev,44,Saint Peterburg,True,Moscow,True,1,12.0
6,Dmitriy,Aksenov,15,Saint Peterburg,False,Kirov,False,1,11.0

6. Получите общую информацию о DataFrame, включая количество строк и столбцов, типы данных и количество ненулевых значений. (метод info)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         7 non-null      str
 1   last_name    7 non-null      str
 2   Age          7 non-null      int64
 3   City         6 non-null      str
 4   is_closed    7 non-null      bool
 5   home_town    6 non-null      str
 6   in_group     7 non-null      bool
 7   male_dummy   7 non-null      int64
 8   likes_memes  6 non-null      float64
dtypes: bool(2), float64(1), int64(2), str(4)
memory usage: 538.0 bytes

----------
### Поля
Кроме методов, у датафреймом есть еще поля. Это справочная информация о датафрейме. Список полей
<a href="https://pandas.pydata.org/pandas-docs/stable/reference/frame.html"> здесь </a>.

Чаще всего мы используем поля:
- **columns**: названия колонок
- **index**: названия строк
- **shape**: размеры датафрейма, кол-во строк и столбцов

Использование:

**[Имя датафрейма].[Имя поля]**

- df.columns
- df.index
- df.shape

Обратите внимание: нет круглых скобок!

7. Выясните сколько в таблице строк и столбцов (метод shape).

In [9]:
df.shape

(7, 9)

8. Выведите на экран названия всех колонок таблицы (метод columns)

In [10]:
df.columns

Index(['Name', 'last_name', 'Age', 'City', 'is_closed', 'home_town',
       'in_group', 'male_dummy', 'likes_memes'],
      dtype='str')

#2. Базовые навыки по работе с табличками

### Выбор колонки

Чтобы вытащить столбец, у нему нужно через квадратные скобки обратиться по имени.

In [11]:
# цепляем head(), чтобы не получить слишком много напечатанных имен
df['Name'].head()

0      Alica
1      Boris
2      Slava
3    Dmitriy
4    Evgenia
Name: Name, dtype: str

In [12]:
# обратите внимание, что в квадратные скобки мы записали только 1 объект - лист с названиями колонок.
t =df[['City', 'Name']].head()
t

              City     Name
0           Moscow    Alica
1           Moscow    Boris
2  Saint Peterburg    Slava
3              NaN  Dmitriy
4           Moscow  Evgenia

Можно создавать новые колонки. Например, мы можем взять все имена и фамилии, записать их через пробел и положить в новую колонку.

In [13]:
t['first_last_name'] = df['Name'] + ' ' + df['last_name']
t.head()

              City     Name   first_last_name
0           Moscow    Alica       Alica Larin
1           Moscow    Boris      Boris Ivanov
2  Saint Peterburg    Slava     Slava Sidorov
3              NaN  Dmitriy  Dmitriy Alekseev
4           Moscow  Evgenia    Evgenia Petrov

### Выбор подряд идущих строк

Если в квадратных скобках указать диапазон, то можно выбрать несколько строк, идущих друг за другом

In [14]:
df[:2]

,Name,last_name,Age,City,is_closed,home_town,in_group,male_dummy,likes_memes
0,Alica,Larin,24,Moscow,False,Samara,True,0,5.0
1,Boris,Ivanov,27,Moscow,True,Saratov,True,1,8.0

In [15]:
df[1:4]

,Name,last_name,Age,City,is_closed,home_town,in_group,male_dummy,likes_memes
1,Boris,Ivanov,27,Moscow,True,Saratov,True,1,8.0
2,Slava,Sidorov,22,Saint Peterburg,False,Saint Peterburg,False,1,44.0
3,Dmitriy,Alekseev,32,NaN,True,NaN,False,1,NaN

---
### Уникальные значения и частотые таблицы

Очень частой операцией является нахождение уникальных значений в колонке. В зависимости от задачи есть два метода.
- [unique()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.unique.html): возвращает массив уникальных значений в колонке - к нему можем применять только обычный питон
- [drop_duplicates()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop_duplicates.html): удаляет дублирующиеся строчки в датафрейме/колонке и возвращает соответственно датафрейм или колонку - к ним можем дальше применять пандасовские методы

- [value_counts()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.value_counts.html): считает частотную таблицу, т.е. сколько раз мы встретили значение в колонке

9. Вытащите из таблички колону с городом (city), примените к ней метод, который оставит в колонке только уникальные названия городов, `.unique()`.

In [16]:
df["City"].dropna().unique()

<StringArray>
['Moscow', 'Saint Peterburg']
Length: 2, dtype: str

10. Сколько всего городов есть в данных?

In [17]:
len(df["City"].dropna().unique())

2

11. Найдите количество уникальных значений в каждом столбце DataFrame.

In [18]:
df.nunique()

Name           5
last_name      7
Age            7
City           2
is_closed      2
home_town      5
in_group       2
male_dummy     2
likes_memes    6
dtype: int64

12. Добавьте новый столбец Salary с произвольными значениями зарплат для каждого человека.

In [19]:
df["Salary"] = np.random.randint(15000, 100000, size=len(df))
df

,Name,last_name,Age,City,is_closed,home_town,in_group,male_dummy,likes_memes,Salary
0,Alica,Larin,24,Moscow,False,Samara,True,0,5.0,96714
1,Boris,Ivanov,27,Moscow,True,Saratov,True,1,8.0,16745
2,Slava,Sidorov,22,Saint Peterburg,False,Saint Peterburg,False,1,44.0,65913
3,Dmitriy,Alekseev,32,NaN,True,NaN,False,1,NaN,19484
4,Evgenia,Petrov,29,Moscow,False,Moscow,True,0,1.0,81305
5,Boris,Lebedev,44,Saint Peterburg,True,Moscow,True,1,12.0,82587
6,Dmitriy,Aksenov,15,Saint Peterburg,False,Kirov,False,1,11.0,67318

13. Измените значение возраста (столбец Age) для любого одного человека.

In [20]:
df.loc[3, "Age"] = 20
df

,Name,last_name,Age,City,is_closed,home_town,in_group,male_dummy,likes_memes,Salary
0,Alica,Larin,24,Moscow,False,Samara,True,0,5.0,96714
1,Boris,Ivanov,27,Moscow,True,Saratov,True,1,8.0,16745
2,Slava,Sidorov,22,Saint Peterburg,False,Saint Peterburg,False,1,44.0,65913
3,Dmitriy,Alekseev,20,NaN,True,NaN,False,1,NaN,19484
4,Evgenia,Petrov,29,Moscow,False,Moscow,True,0,1.0,81305
5,Boris,Lebedev,44,Saint Peterburg,True,Moscow,True,1,12.0,82587
6,Dmitriy,Aksenov,15,Saint Peterburg,False,Kirov,False,1,11.0,67318

14. Какая доля людей закрыла профиль (is_closed)?

In [21]:
df["is_closed"].mean()

np.float64(0.42857142857142855)

15. Отфильтруйте строки DataFrame, где возраст больше 25 лет.

In [22]:
df[df["Age"] > 25]

,Name,last_name,Age,City,is_closed,home_town,in_group,male_dummy,likes_memes,Salary
1,Boris,Ivanov,27,Moscow,True,Saratov,True,1,8.0,16745
4,Evgenia,Petrov,29,Moscow,False,Moscow,True,0,1.0,81305
5,Boris,Lebedev,44,Saint Peterburg,True,Moscow,True,1,12.0,82587

16. Отфильтруйте строки, где город равен "Moscow".

In [23]:
df[df["City"] == "Moscow"]

,Name,last_name,Age,City,is_closed,home_town,in_group,male_dummy,likes_memes,Salary
0,Alica,Larin,24,Moscow,False,Samara,True,0,5.0,96714
1,Boris,Ivanov,27,Moscow,True,Saratov,True,1,8.0,16745
4,Evgenia,Petrov,29,Moscow,False,Moscow,True,0,1.0,81305

17. Попробуйте вытащить ту же самую колонку и посчитать по ней, как часто, какой город встречается в данных, `.value_counts()`

In [24]:
df["City"].value_counts()

City
Moscow             3
Saint Peterburg    3
Name: count, dtype: int64

18. Выведите на экран $2$ самых популярных городов в датафрейме

In [25]:
df["City"].value_counts().head(2)

City
Moscow             3
Saint Peterburg    3
Name: count, dtype: int64

19. Сгруппируйте данные по столбцу City и найдите средний возраст людей для каждого города. .groupby()

In [26]:
df.groupby("City")["Age"].mean()

City
Moscow             26.666667
Saint Peterburg    27.000000
Name: Age, dtype: float64

20. Используйте loc, чтобы выбрать строки с именем "Alica" и "Evgenia" и вывести соответствующие данные.

In [27]:
df.loc[df["Name"].isin(["Alica", "Evgenia"])]

,Name,last_name,Age,City,is_closed,home_town,in_group,male_dummy,likes_memes,Salary
0,Alica,Larin,24,Moscow,False,Samara,True,0,5.0,96714
4,Evgenia,Petrov,29,Moscow,False,Moscow,True,0,1.0,81305

21. Используйте loc, чтобы изменить значение зарплаты для человека по имени "Dmitriy" на 70000.

In [28]:
df.loc[df["Name"] == "Dmitriy", "Salary"] = 70000
df[df["Name"] == "Dmitriy"]

,Name,last_name,Age,City,is_closed,home_town,in_group,male_dummy,likes_memes,Salary
3,Dmitriy,Alekseev,20,NaN,True,NaN,False,1,NaN,70000
6,Dmitriy,Aksenov,15,Saint Peterburg,False,Kirov,False,1,11.0,70000

22. Используйте loc, чтобы выбрать и вывести данные всех людей старше 30 лет.

In [29]:
df.loc[df["Age"] > 30]

,Name,last_name,Age,City,is_closed,home_town,in_group,male_dummy,likes_memes,Salary
5,Boris,Lebedev,44,Saint Peterburg,True,Moscow,True,1,12.0,82587

23. Сколько уникальных мужских имён встречается?

In [30]:
len(df.loc[df["male_dummy"] == 1, "Name"].unique())

3

24. Выведите два самых популярных мужских имени

In [31]:
df.loc[df["male_dummy"] == 1, "Name"].value_counts().head(2)

Name
Boris      2
Dmitriy    2
Name: count, dtype: int64

25. Сколько в среднем лайков ставят под мемы девушки (колонка likes_memes)

In [32]:
df.loc[df["male_dummy"] == 0, "likes_memes"].mean()

np.float64(3.0)

26. Сколько суммарно лайков оставили студенты в группе с мемами?

In [33]:
df["likes_memes"].sum()

np.float64(81.0)

27. Сколько в среднем лайков приходится на одного человека, подписанного на группу (колонка in_group)

In [34]:
df.loc[df["in_group"] == True, "likes_memes"].mean()

np.float64(6.5)

28. Сколько лайков поставили люди, которые не подписаны на группу?

In [35]:
df.loc[df["in_group"] == False, "likes_memes"].sum()

np.float64(55.0)

29. Выведите на экран колонки, в которых нет ни одного пропуска.

In [36]:
df[df.columns[df.isnull().sum() == 0]]

      Name last_name  Age  is_closed  in_group  male_dummy  Salary
0    Alica     Larin   24      False      True           0   96714
1    Boris    Ivanov   27       True      True           1   16745
2    Slava   Sidorov   22      False     False           1   65913
3  Dmitriy  Alekseev   20       True     False           1   70000
4  Evgenia    Petrov   29      False      True           0   81305
5    Boris   Lebedev   44       True      True           1   82587
6  Dmitriy   Aksenov   15      False     False           1   70000

30.  Сейчас число лайков измеряется по шкале от $0$ до $44$. В машинном обучении довольно часто возникает желание поменять у данных шкалу, в которой они измерены. Такая процедура называется скалированием. Давайте переведём лайки с отрезка $[0, 44]$ на отрезок $[0, 1]$. Делать это будем по формуле:

        x_new = (x-min)/(max-min)
    
        min = минимальный элемент в столбце
        max = максимальный элемент в столбце
        
Получившийся результат запишем в колонку `like_memes_scal`.

In [37]:
min = df["likes_memes"].min()
max = df["likes_memes"].max()
df["likes_memes_scal"] = (df["likes_memes"] - min) / (max - min)
df

,Name,last_name,Age,City,is_closed,home_town,in_group,male_dummy,likes_memes,Salary,likes_memes_scal
0,Alica,Larin,24,Moscow,False,Samara,True,0,5.0,96714,0.093023
1,Boris,Ivanov,27,Moscow,True,Saratov,True,1,8.0,16745,0.162791
2,Slava,Sidorov,22,Saint Peterburg,False,Saint Peterburg,False,1,44.0,65913,1.000000
3,Dmitriy,Alekseev,20,NaN,True,NaN,False,1,NaN,70000,NaN
4,Evgenia,Petrov,29,Moscow,False,Moscow,True,0,1.0,81305,0.000000
5,Boris,Lebedev,44,Saint Peterburg,True,Moscow,True,1,12.0,82587,0.255814
6,Dmitriy,Aksenov,15,Saint Peterburg,False,Kirov,False,1,11.0,70000,0.232558

31. Найдите суммарную зарплату для каждого города

In [38]:
df.groupby("City")["Salary"].sum()

City
Moscow             194764
Saint Peterburg    218500
Name: Salary, dtype: int32

32. Используйте where, чтобы заменить все значения возраста, которые меньше 25, на NaN.

In [39]:
df["Age"] = df["Age"].where(df["Age"] >= 25, np.nan)
df

,Name,last_name,Age,City,is_closed,home_town,in_group,male_dummy,likes_memes,Salary,likes_memes_scal
0,Alica,Larin,NaN,Moscow,False,Samara,True,0,5.0,96714,0.093023
1,Boris,Ivanov,27.0,Moscow,True,Saratov,True,1,8.0,16745,0.162791
2,Slava,Sidorov,NaN,Saint Peterburg,False,Saint Peterburg,False,1,44.0,65913,1.000000
3,Dmitriy,Alekseev,NaN,NaN,True,NaN,False,1,NaN,70000,NaN
4,Evgenia,Petrov,29.0,Moscow,False,Moscow,True,0,1.0,81305,0.000000
5,Boris,Lebedev,44.0,Saint Peterburg,True,Moscow,True,1,12.0,82587,0.255814
6,Dmitriy,Aksenov,NaN,Saint Peterburg,False,Kirov,False,1,11.0,70000,0.232558

33. Используйте where, чтобы заменить все значения зарплаты, которые меньше 60000, на 12000.

In [40]:
df["Salary"] = df["Salary"].where(df["Salary"] >= 60000, 12000)
df

,Name,last_name,Age,City,is_closed,home_town,in_group,male_dummy,likes_memes,Salary,likes_memes_scal
0,Alica,Larin,NaN,Moscow,False,Samara,True,0,5.0,96714,0.093023
1,Boris,Ivanov,27.0,Moscow,True,Saratov,True,1,8.0,12000,0.162791
2,Slava,Sidorov,NaN,Saint Peterburg,False,Saint Peterburg,False,1,44.0,65913,1.000000
3,Dmitriy,Alekseev,NaN,NaN,True,NaN,False,1,NaN,70000,NaN
4,Evgenia,Petrov,29.0,Moscow,False,Moscow,True,0,1.0,81305,0.000000
5,Boris,Lebedev,44.0,Saint Peterburg,True,Moscow,True,1,12.0,82587,0.255814
6,Dmitriy,Aksenov,NaN,Saint Peterburg,False,Kirov,False,1,11.0,70000,0.232558

34. Создайте многоуровневый индекс 'City' и 'Name'

In [41]:
df = df.set_index(["City", "Name"])
df

                        last_name   Age  is_closed        home_town  in_group  \
City            Name
Moscow          Alica       Larin   NaN      False           Samara      True
                Boris      Ivanov  27.0       True          Saratov      True
Saint Peterburg Slava     Sidorov   NaN      False  Saint Peterburg     False
nan             Dmitriy  Alekseev   NaN       True              NaN     False
Moscow          Evgenia    Petrov  29.0      False           Moscow      True
Saint Peterburg Boris     Lebedev  44.0       True           Moscow      True
                Dmitriy   Aksenov   NaN      False            Kirov     False

                         male_dummy  likes_memes  Salary  likes_memes_scal
City            Name
Moscow          Alica             0          5.0   96714          0.093023
                Boris             1          8.0   12000          0.162791
Saint Peterburg Slava             1         44.0   65913          1.000000
nan             Dmitriy           1          NaN   70000               NaN
Moscow          Evgenia           0          1.0   81305          0.000000
Saint Peterburg Boris             1         12.0   82587          0.255814
                Dmitriy           1         11.0   70000          0.232558

35. Используйте xs, чтобы выбрать данные для города "Moscow"

In [42]:
df.xs("Moscow", level="City")

,last_name,Age,is_closed,home_town,in_group,male_dummy,likes_memes,Salary,likes_memes_scal
Name,,,,,,,,,
Alica,Larin,NaN,False,Samara,True,0,5.0,96714,0.093023
Boris,Ivanov,27.0,True,Saratov,True,1,8.0,12000,0.162791
Evgenia,Petrov,29.0,False,Moscow,True,0,1.0,81305,0.000000

36. Используйте xs, чтобы выбрать данные для человека с именем "Boris"

In [43]:
df.xs("Boris", level="Name")

,last_name,Age,is_closed,home_town,in_group,male_dummy,likes_memes,Salary,likes_memes_scal
City,,,,,,,,,
Moscow,Ivanov,27.0,True,Saratov,True,1,8.0,12000,0.162791
Saint Peterburg,Lebedev,44.0,True,Moscow,True,1,12.0,82587,0.255814

37. Вычислите суммарную зарплату всех людей.

In [44]:
df["Salary"].sum()

np.int64(478519)

38. Вычислите среднюю зарплату всех людей нашего Dataframe.

In [45]:
df["Salary"].mean()

np.float64(68359.85714285714)

39. Вычислите медиану возраста сотрудников.

In [46]:
df["Age"].median()

np.float64(29.0)

40. Вычислите стандартное отклонение зарплаты

In [47]:
df["Salary"].std()

np.float64(26962.15396581272)

41. Вычислите минимальную и максимальную зарплату

In [48]:
min = df["Salary"].min()
max = df["Salary"].max()
min, max

(np.int32(12000), np.int32(96714))

42. Вычислите минимальный и максимальный возраст сотрудников.

In [49]:
min = df["Age"].min()
max = df["Age"].max()
min, max

(np.float64(27.0), np.float64(44.0))